version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
    volumes:
      - ./minecraftData:/data
    healthcheck:
      test: ["CMD", "mc-health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    restart: unless-stopped
    networks:
      - minecraft_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backup:
    image: itzg/mc-backup
    container_name: minecraft-backup
    restart: unless-stopped
    environment:
      - BACKUP_INTERVAL=6h
      - RCON_HOST=minecraft
      - PRE_BACKUP_SCRIPT=/scripts/pre-backup.sh
    volumes:
      - ./backups:/backups
      - ./scripts:/scripts
      - ./minecraftData:/data:ro
    networks:
      - minecraft_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    restart: unless-stopped
    command: start --all --config /etc/ngrok/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok/ngrok.yml
    ports:
      - "4040:4040"
    networks:
      - minecraft_network

networks:
  minecraft_network:
    driver: bridge
