apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: NodePort # Use LoadBalancer if your cluster supports it (e.g., on a cloud provider)
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30000 # You can choose a port in the 30000-32767 range
